package cn.source.pojo;

import java.io.Serializable;

public class Mould implements Serializable {
    /**
     * 模板id
     * 表字段 : mould.mId
     */
    private Integer mid;

    /**
     * 模板名称
     * 表字段 : mould.mName
     */
    private String mname;

    /**
     * 分类id(外键)
     * 表字段 : mould.tId
     */
    private Integer tid;

    /**
     * 标签
     * 表字段 : mould.label
     */
    private String label;

    /**
     * 点赞数
     * 表字段 : mould.praise
     */
    private Integer praise;

    /**
     * 踩数量
     * 表字段 : mould.tread
     */
    private Integer tread;

    /**
     * 图片
     * 表字段 : mould.img
     */
    private String img;

    /**
     * logo
     * 表字段 : mould.logo
     */
    private String logo;

    /**
     * 预览地址
     * 表字段 : mould.preview
     */
    private String preview;

    /**
     * 下载链接
     * 表字段 : mould.download
     */
    private String download;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mould
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 模板id 字段:mould.mId
     *
     * @return mould.mId, 模板id
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * 设置 模板id 字段:mould.mId
     *
     * @param mid the value for mould.mId, 模板id
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * 获取 模板名称 字段:mould.mName
     *
     * @return mould.mName, 模板名称
     */
    public String getMname() {
        return mname;
    }

    /**
     * 设置 模板名称 字段:mould.mName
     *
     * @param mname the value for mould.mName, 模板名称
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * 获取 分类id(外键) 字段:mould.tId
     *
     * @return mould.tId, 分类id(外键)
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * 设置 分类id(外键) 字段:mould.tId
     *
     * @param tid the value for mould.tId, 分类id(外键)
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * 获取 标签 字段:mould.label
     *
     * @return mould.label, 标签
     */
    public String getLabel() {
        return label;
    }

    /**
     * 设置 标签 字段:mould.label
     *
     * @param label the value for mould.label, 标签
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * 获取 点赞数 字段:mould.praise
     *
     * @return mould.praise, 点赞数
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * 设置 点赞数 字段:mould.praise
     *
     * @param praise the value for mould.praise, 点赞数
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * 获取 踩数量 字段:mould.tread
     *
     * @return mould.tread, 踩数量
     */
    public Integer getTread() {
        return tread;
    }

    /**
     * 设置 踩数量 字段:mould.tread
     *
     * @param tread the value for mould.tread, 踩数量
     */
    public void setTread(Integer tread) {
        this.tread = tread;
    }

    /**
     * 获取 图片 字段:mould.img
     *
     * @return mould.img, 图片
     */
    public String getImg() {
        return img;
    }

    /**
     * 设置 图片 字段:mould.img
     *
     * @param img the value for mould.img, 图片
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * 获取 logo 字段:mould.logo
     *
     * @return mould.logo, logo
     */
    public String getLogo() {
        return logo;
    }

    /**
     * 设置 logo 字段:mould.logo
     *
     * @param logo the value for mould.logo, logo
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * 获取 预览地址 字段:mould.preview
     *
     * @return mould.preview, 预览地址
     */
    public String getPreview() {
        return preview;
    }

    /**
     * 设置 预览地址 字段:mould.preview
     *
     * @param preview the value for mould.preview, 预览地址
     */
    public void setPreview(String preview) {
        this.preview = preview == null ? null : preview.trim();
    }

    /**
     * 获取 下载链接 字段:mould.download
     *
     * @return mould.download, 下载链接
     */
    public String getDownload() {
        return download;
    }

    /**
     * 设置 下载链接 字段:mould.download
     *
     * @param download the value for mould.download, 下载链接
     */
    public void setDownload(String download) {
        this.download = download == null ? null : download.trim();
    }
}