package cn.source.pojo;

import java.io.Serializable;
import java.util.Date;

public class Notice implements Serializable {
    /**
     * 公告id
     * 表字段 : notice.nId
     */
    private Integer nid;

    /**
     * 公告标题
     * 表字段 : notice.title
     */
    private String title;

    /**
     * 公告内容
     * 表字段 : notice.context
     */
    private String context;

    /**
     * 公告发布时间
     * 表字段 : notice.dateLine
     */
    private Date dateline;

    /**
     * 公告的首图
     * 表字段 : notice.img
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 公告id 字段:notice.nId
     *
     * @return notice.nId, 公告id
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * 设置 公告id 字段:notice.nId
     *
     * @param nid the value for notice.nId, 公告id
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * 获取 公告标题 字段:notice.title
     *
     * @return notice.title, 公告标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置 公告标题 字段:notice.title
     *
     * @param title the value for notice.title, 公告标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取 公告内容 字段:notice.context
     *
     * @return notice.context, 公告内容
     */
    public String getContext() {
        return context;
    }

    /**
     * 设置 公告内容 字段:notice.context
     *
     * @param context the value for notice.context, 公告内容
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * 获取 公告发布时间 字段:notice.dateLine
     *
     * @return notice.dateLine, 公告发布时间
     */
    public Date getDateline() {
        return dateline;
    }

    /**
     * 设置 公告发布时间 字段:notice.dateLine
     *
     * @param dateline the value for notice.dateLine, 公告发布时间
     */
    public void setDateline(Date dateline) {
        this.dateline = dateline;
    }

    /**
     * 获取 公告的首图 字段:notice.img
     *
     * @return notice.img, 公告的首图
     */
    public String getImg() {
        return img;
    }

    /**
     * 设置 公告的首图 字段:notice.img
     *
     * @param img the value for notice.img, 公告的首图
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}