package cn.source.pojo;

import java.io.Serializable;

public class Star implements Serializable {
    /**
     * 收藏id
     * 表字段 : star.sid
     */
    private Integer sid;

    /**
     * 用户id
     * 表字段 : star.uId
     */
    private Integer uid;

    /**
     * 模板id
     * 表字段 : star.mId
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table star
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 收藏id 字段:star.sid
     *
     * @return star.sid, 收藏id
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * 设置 收藏id 字段:star.sid
     *
     * @param sid the value for star.sid, 收藏id
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * 获取 用户id 字段:star.uId
     *
     * @return star.uId, 用户id
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * 设置 用户id 字段:star.uId
     *
     * @param uid the value for star.uId, 用户id
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * 获取 模板id 字段:star.mId
     *
     * @return star.mId, 模板id
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * 设置 模板id 字段:star.mId
     *
     * @param mid the value for star.mId, 模板id
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}