package cn.source.pojo;

import java.io.Serializable;

public class TagCloud implements Serializable {
    /**
     * 标签云id
     * 表字段 : tagcloud.tId
     */
    private Integer tid;

    /**
     * 标签云名称
     * 表字段 : tagcloud.tName
     */
    private String tname;

    /**
     * 标签云下的数量
     * 表字段 : tagcloud.amount
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tagcloud
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 标签云id 字段:tagcloud.tId
     *
     * @return tagcloud.tId, 标签云id
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * 设置 标签云id 字段:tagcloud.tId
     *
     * @param tid the value for tagcloud.tId, 标签云id
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * 获取 标签云名称 字段:tagcloud.tName
     *
     * @return tagcloud.tName, 标签云名称
     */
    public String getTname() {
        return tname;
    }

    /**
     * 设置 标签云名称 字段:tagcloud.tName
     *
     * @param tname the value for tagcloud.tName, 标签云名称
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * 获取 标签云下的数量 字段:tagcloud.amount
     *
     * @return tagcloud.amount, 标签云下的数量
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * 设置 标签云下的数量 字段:tagcloud.amount
     *
     * @param amount the value for tagcloud.amount, 标签云下的数量
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}