package cn.source.pojo;

import java.io.Serializable;

public class Tarde implements Serializable {
    /**
     * 行业id
     * 表字段 : tarde.tId
     */
    private Integer tid;

    /**
     * 行业名称
     * 表字段 : tarde.tName
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tarde
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 行业id 字段:tarde.tId
     *
     * @return tarde.tId, 行业id
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * 设置 行业id 字段:tarde.tId
     *
     * @param tid the value for tarde.tId, 行业id
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * 获取 行业名称 字段:tarde.tName
     *
     * @return tarde.tName, 行业名称
     */
    public String getTname() {
        return tname;
    }

    /**
     * 设置 行业名称 字段:tarde.tName
     *
     * @param tname the value for tarde.tName, 行业名称
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }
}